server:
  port: 9100
  contextPath: /search


activemq:
  broker-url: tcp://localhost:61616
  queue:
    renteCreated: rentes.q

elasticsearch:
  clustername: docker-cluster
  host: localhost
  port: 9300
