#####################################################################
# Configuration Spring de base
#####################################################################
server:
  port:                                     8100


spring:
  application:
    name:                                   config-server
  profiles:
    active:                                 default

#####################################################################
# Configuration Spring cloud
#####################################################################
  cloud:
    config:

      server:
        git:
          uri:                              http://gitlab.ju.globaz.ch/AVS4.0/archi-distribuee-config.git

      # ne pas ecraser les arguments jvm
      overrideSystemProperties:             false
      overrideNone:                         true
#####################################################################
# Configuration Spring actuator
#####################################################################
management:
  security:
    enabled:                                 false
  context-path:                              /actuator

# configuration des endpoints
endpoints:
  hypermedia:
    enabled:                                 true

  actuator:
    enabled:                                 true

  beans:
    enabled:                                 true

  env:
    enabled:                                 true

  metrics:
    enabled:                                 true

  health:
    enabled:                                 true

  mappings:
    enabled:                                 true

  docs:
    enabled:                                 true

  logfile:
    enabled:                                 true